# Generated by Django 2.2.10 on 2020-07-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enviroinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128, verbose_name='Nome do ambiente')),
                ('ip', models.GenericIPAddressField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('enviroinment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enviroinment.Enviroinment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
